#!/usr/bin/env python3
"""Send optional notifications after pipeline generation."""

from __future__ import annotations

import argparse
import json
import logging
import os
from datetime import datetime
from pathlib import Path
from typing import Optional, Tuple

import requests

BASE_DIR = Path(__file__).resolve().parents[1]
DATA_DIR = BASE_DIR / "data"

logging.basicConfig(
    level=os.getenv("LOG_LEVEL", "INFO").upper(),
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
)
logger = logging.getLogger("notify")


def utc_now() -> str:
    return datetime.utcnow().isoformat() + "Z"


def load_blocklist_summary(path: Path) -> dict:
    if not path.exists():
        return {
            "total_domains": 0,
            "updated": utc_now(),
        }

    with path.open("r", encoding="utf-8") as fh:
        data = json.load(fh)

    stats = data.get("statistics", {}) if isinstance(data, dict) else {}
    return {
        "total_domains": stats.get("total_domains", len(data.get("blocklist", [])) if isinstance(data, dict) else 0),
        "updated": data.get("created_at", utc_now()) if isinstance(data, dict) else utc_now(),
    }


def load_pipeline_health(path: Path) -> dict:
    if not path.exists():
        return {
            "status": "unknown",
            "stale": False,
            "reasons": [],
        }

    try:
        with path.open("r", encoding="utf-8") as fh:
            data = json.load(fh)
    except Exception:
        return {
            "status": "unknown",
            "stale": False,
            "reasons": [],
        }

    if not isinstance(data, dict):
        return {
            "status": "unknown",
            "stale": False,
            "reasons": [],
        }

    return {
        "status": str(data.get("status", "unknown")),
        "stale": bool(data.get("stale", False)),
        "reasons": data.get("reasons", []) if isinstance(data.get("reasons", []), list) else [],
        "freshness": data.get("freshness", {}),
        "generated_at": data.get("generated_at", utc_now()),
    }


def send_discord(webhook_url: str, message: str) -> Tuple[bool, Optional[str]]:
    try:
        resp = requests.post(webhook_url, json={"content": message}, timeout=10)
    except Exception as exc:
        return False, f"request_exception: {exc}"

    if 200 <= resp.status_code < 300:
        return True, None

    body = (resp.text or "").strip().replace("\n", " ")[:300]
    return False, f"http_{resp.status_code}: {body or 'empty_response_body'}"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Send pipeline notifications")
    parser.add_argument(
        "--blocklist",
        default=str(DATA_DIR / "blocklist.json"),
        help="Path to generated blocklist",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="Fail with non-zero exit code when webhook delivery fails",
    )
    parser.add_argument(
        "--pipeline-health",
        default=str(DATA_DIR / "pipeline_health.json"),
        help="Path to pipeline health JSON generated by consolidator",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    summary = load_blocklist_summary(Path(args.blocklist))
    pipeline_health = load_pipeline_health(Path(args.pipeline_health))
    strict_mode = args.strict or os.getenv("NOTIFY_STRICT", "false").strip().lower() == "true"

    stale_flag = bool(pipeline_health.get("stale", False))
    stale_reasons = pipeline_health.get("reasons", []) if isinstance(pipeline_health.get("reasons", []), list) else []

    message = (
        "Anti-Judol pipeline update\n"
        f"- Total domains: {summary['total_domains']}\n"
        f"- Updated: {summary['updated']}\n"
        f"- Health status: {pipeline_health.get('status', 'unknown')}\n"
        f"- Data stale: {'yes' if stale_flag else 'no'}"
    )
    if stale_reasons:
        message += f"\n- Stale reasons: {', '.join([str(x) for x in stale_reasons])}"

    webhook = os.getenv("DISCORD_WEBHOOK_URL", "").strip()
    sent = False
    error_detail: Optional[str] = None
    if webhook:
        sent, error_detail = send_discord(webhook, message)
        if not sent:
            logger.warning("discord notification failed: %s", error_detail)
            if strict_mode:
                result = {
                    "timestamp": utc_now(),
                    "webhook_configured": True,
                    "discord_sent": False,
                    "strict_mode": True,
                    "discord_error": error_detail,
                    "stale_data": stale_flag,
                    "stale_reasons": stale_reasons,
                    "pipeline_health": pipeline_health,
                    "message": message,
                }
                print(json.dumps(result, indent=2))
                return 1
    else:
        logger.info("discord webhook not configured; skipping notification")

    if stale_flag:
        logger.warning("pipeline health marked stale: %s", ", ".join([str(x) for x in stale_reasons]) or "no reason")
        if strict_mode:
            result = {
                "timestamp": utc_now(),
                "webhook_configured": bool(webhook),
                "discord_sent": sent,
                "strict_mode": True,
                "discord_error": error_detail,
                "stale_data": True,
                "stale_reasons": stale_reasons,
                "pipeline_health": pipeline_health,
                "message": message,
            }
            print(json.dumps(result, indent=2))
            return 1

    result = {
        "timestamp": utc_now(),
        "webhook_configured": bool(webhook),
        "discord_sent": sent,
        "strict_mode": strict_mode,
        "discord_error": error_detail,
        "stale_data": stale_flag,
        "stale_reasons": stale_reasons,
        "pipeline_health": pipeline_health,
        "message": message,
    }
    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
